extends: standard

overrides:
  -
    files: [ '*.mjs' ]
    rules:
      no-restricted-globals: [ 2, require, __dirname ]
  -
    files: [ 'lib/**', 'index.mjs' ]
    parserOptions: { ecmaVersion: 2015 }

ignorePatterns:
  - demo/
  - dist/
  - benchmark/extra/
  - test/browser/bundled.js

rules:
  camelcase: 0
  no-multi-spaces: 0
